# Generated by Django 5.2.4 on 2025-07-26 12:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=10)),
                ('mobile_number', models.CharField(max_length=15, unique=True)),
                ('email_id', models.EmailField(max_length=254, unique=True)),
                ('address1', models.TextField()),
                ('address2', models.TextField(blank=True, null=True)),
                ('pincode', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('aadhar_number', models.CharField(max_length=12, unique=True)),
                ('pan_card_number', models.CharField(max_length=10, unique=True)),
                ('leg_number', models.CharField(blank=True, max_length=20, unique=True)),
                ('account_number', models.CharField(blank=True, max_length=20, unique=True)),
                ('cif_id', models.CharField(blank=True, max_length=20, unique=True)),
                ('asacass_number', models.CharField(blank=True, max_length=20, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Personal Details',
            },
        ),
        migrations.CreateModel(
            name='NomineeDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nominee_name', models.CharField(max_length=200)),
                ('nominee_relation', models.CharField(max_length=50)),
                ('nominee_date_of_birth', models.DateField()),
                ('nominee_mobile_number', models.CharField(max_length=15)),
                ('nominee_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('nominee_address', models.TextField()),
                ('nominee_aadhar_number', models.CharField(max_length=12)),
                ('nominee_pan_card_number', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('personal_details', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='nominee_details', to='accounts.personaldetails')),
            ],
            options={
                'verbose_name_plural': 'Nominee Details',
            },
        ),
        migrations.CreateModel(
            name='FamilyDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spouse_name', models.CharField(blank=True, max_length=200, null=True)),
                ('spouse_occupation', models.CharField(blank=True, max_length=100, null=True)),
                ('children_count', models.PositiveIntegerField(default=0)),
                ('children_details', models.TextField(blank=True, null=True)),
                ('father_name', models.CharField(max_length=200)),
                ('mother_name', models.CharField(max_length=200)),
                ('emergency_contact_name', models.CharField(max_length=200)),
                ('emergency_contact_relation', models.CharField(max_length=50)),
                ('emergency_contact_mobile', models.CharField(max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('personal_details', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='family_details', to='accounts.personaldetails')),
            ],
            options={
                'verbose_name_plural': 'Family Details',
            },
        ),
        migrations.CreateModel(
            name='AccountDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_type', models.CharField(choices=[('SAVINGS', 'Savings Account'), ('CURRENT', 'Current Account'), ('FIXED_DEPOSIT', 'Fixed Deposit'), ('RECURRING_DEPOSIT', 'Recurring Deposit')], max_length=20)),
                ('scheme_type', models.CharField(choices=[('REGULAR', 'Regular'), ('SENIOR_CITIZEN', 'Senior Citizen'), ('STUDENT', 'Student'), ('WOMEN', 'Women'), ('RURAL', 'Rural')], max_length=20)),
                ('date_of_opening', models.DateField(auto_now_add=True)),
                ('maturity_date', models.DateField(blank=True, null=True)),
                ('deposit_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('current_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('is_active', models.BooleanField(default=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('branch_code', models.CharField(default='MAIN001', max_length=10)),
                ('interest_rate', models.DecimalField(decimal_places=2, default=3.5, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('personal_details', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='account_details', to='accounts.personaldetails')),
            ],
            options={
                'verbose_name_plural': 'Account Details',
            },
        ),
    ]
